#修改内嵌容器的端口号
#server:
#  port: 8888

#配置自定义属性
name: spring-boot-yml
author: https://github.com/550690513
#配置变量的引用
hello:
  msg: This is a Application named by "${name}".
  msg2: hello（this msg comes from `application.yml` file）

#生成随机值（配置文件只有在项目启动时才被解析一次，所以该随机值生成后就不会改变了）
randomInt: ${random.int}

#配置动态端口号（固定范围随机生成）
#用处：在SpringCloud微服务中，是不需要记录IP与端口号的。那么也就不需要去维护服务的端口号，端口号随机生成即可。
server:
  port: ${random.int[1024,9999]}